#version 460
#define STORAGE_IMAGES
#include "common.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

layout(push_constant, scalar) uniform Push {
    uint source_texture;
    uint sampler_index;
    uint first;
    int source_lod;
    uint target;
    uint pad;
    ivec2 size;
} push;

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(pixel, push.size))) return;
    float a;
    float b;
    float c;
    float d;
    if (push.first != 0u) {
        vec2 texel = 1.0 / vec2(push.size);
        vec2 uv = (vec2(pixel) + 0.5) * texel;
        vec2 offset = texel * 0.25;
        a = textureLod(TEX(push.source_texture, push.sampler_index), uv + vec2(-offset.x, -offset.y), 0.0).r;
        b = textureLod(TEX(push.source_texture, push.sampler_index), uv + vec2(offset.x, -offset.y), 0.0).r;
        c = textureLod(TEX(push.source_texture, push.sampler_index), uv + vec2(-offset.x, offset.y), 0.0).r;
        d = textureLod(TEX(push.source_texture, push.sampler_index), uv + vec2(offset.x, offset.y), 0.0).r;
    } else {
        ivec2 base = pixel * 2;
        ivec2 limit = textureSize(TEX(push.source_texture, push.sampler_index), push.source_lod) - 1;
        a = texelFetch(TEX(push.source_texture, push.sampler_index), min(base, limit), push.source_lod).r;
        b = texelFetch(TEX(push.source_texture, push.sampler_index), min(base + ivec2(1, 0), limit), push.source_lod).r;
        c = texelFetch(TEX(push.source_texture, push.sampler_index), min(base + ivec2(0, 1), limit), push.source_lod).r;
        d = texelFetch(TEX(push.source_texture, push.sampler_index), min(base + ivec2(1, 1), limit), push.source_lod).r;
    }
    imageStore(STORAGE(push.target), pixel, vec4(min(min(a, b), min(c, d))));
}
